# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

dotenv:
  - .env

vars:
  # Frequently changed
  SERVICES: mysql nginx
  REPO_DIR: /home/isucon/repo
  SRC_DIR: /home/isucon/repo/app/go

  # Rarely changed
  SQLITE_TRACE_LOG: /home/isucon/tmp/trace.log
  SQLITE_TRACE_LOG_SORTED: /home/isucon/tmp/sqlite-slow.json

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: Deploy the latest configuration
    deps:
      - checkout
    dir: "{{.REPO_DIR}}"
    cmds:
      - task: build
      - ./assets/distribute_config.sh
      - task: restart-all
      - task: reload-sysctl
      - truncate -s 0 {{.SQLITE_TRACE_LOG}}

  build:
    desc: Build the application
    dir: "{{.SRC_DIR}}"
    cmds:
      - sudo systemctl restart --now isuports

  ####################
  #     Utility      #
  ####################
  checkout:
    desc: Checkout and sync with the latest remote branch
    dir: "{{.REPO_DIR}}"
    vars:
      BRANCH: '{{.CLI_ARGS | default "main"}}'
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  enable:
    desc: Enable and start specified services
    cmds:
      - sudo systemctl enable --now {{.CLI_ARGS}}

  disable:
    desc: Disable and stop specified services
    cmds:
      - sudo systemctl disable --now {{.CLI_ARGS}}

  status:
    desc: Show status of specified services
    cmds:
      - sudo systemctl status {{.CLI_ARGS}}

  status-all:
    desc: Show status of all services related to the application
    cmds:
      - sudo systemctl status {{.SERVICES}}

  restart:
    desc: Restart specified services
    deps:
      - daemon-reload
    cmds:
      - sudo systemctl restart {{.CLI_ARGS}}

  restart-all:
    desc: Restart all services related to the application
    deps:
      - daemon-reload
    cmds:
      - sudo systemctl restart {{.SERVICES}}

  reload-sysctl:
    desc: Reload sysctl configuration
    cmds:
      - sudo sysctl -p

  # DISCORD_WEBHOOK はホストに手動で配置しました
  send-trace:
    desc: Send SQLite trace log to Discord
    cmds:
      - task: aggregate-trace
        silent: true
      - cmd: http -f "$DISCORD_WEBHOOK" file@{{.SQLITE_TRACE_LOG_SORTED}}
        silent: true

  ####################
  #     Internal     #
  ####################
  daemon-reload:
    - sudo systemctl daemon-reload

  aggregate-trace:
    - |
      jq -s '
        group_by(.statement) |
        map({
          statement: .[0].statement,
          count: length,
          total_time: (map(.query_time) | add)
        }) |
        sort_by(-.total_time) |
        .[:10]
      ' < {{.SQLITE_TRACE_LOG}} > {{.SQLITE_TRACE_LOG_SORTED}}
